[package]
name = "untitled"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build]
target = "aarch64-apple-darwin"

[target.'cfg(target_os = "macos")'.dependencies]
sdl2 = "0.34.5"
